### ISSUE TITLE
Database version upgrades

### ISSUE THREAD

**Issue by pmig** [mmontes11/mariadb-operator#19]
Thank you for your operator. It works quite well! (Despite the helm repo https://charts.mmontes-dev.duckdns.org/ is often not available)

MariaDB Version Tags are immutable.

What is the recommanded upgrade path?

**Comment by mmontes11** [comment]
Thanks a lot!

Regarding the helm repo, I've just updated the [docs](https://github.com/mmontes11/mariadb-operator/blob/main/README.md#installation) pointing to the new one (https://charts.mmontes.duckdns.org ). We have some plans to improve the experience installing our chart:
- https://github.com/mmontes11/mariadb-operator/issues/20
- https://github.com/mmontes11/mariadb-operator/issues/10

> MariaDB Version Tags are immutable
> What is the recommanded upgrade path

That's right, this is not documented yet but the unoficcial approach would be 
1. Create a `MariaDB` resource
```yaml
apiVersion: database.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
  image:
    repository: mariadb
    tag: "10.7.4"
    pullPolicy: IfNotPresent
  port: 3306
  volumeClaimTemplate:
    resources:
      requests:
        storage: 100Mi
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
```
2. Take a backup
```yaml
apiVersion: database.mmontes.io/v1alpha1
kind: BackupMariaDB
metadata:
  name: backup
spec:
  mariaDbRef:
    name: mariadb
  storage:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 100Mi
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
 ```
 3. Create a new `MariaDB` instance bumping the version and bootstrapping for backup:
 ``` yaml
 apiVersion: database.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-from-backup
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  database: mariadb
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb
    key: password

  image:
    repository: mariadb
    tag: "10.7.4"
    pullPolicy: IfNotPresent

  port: 3306

  volumeClaimTemplate:
    resources:
      requests:
        storage: 100Mi
    storageClassName: standard
    accessModes:
      - ReadWriteOnce

  bootstrapFromBackupRef:
    name: backup
 ``` 
 
When the new one is marked as `Ready` you can swap the labels in your `Service` to forward the traffic to it. I hope it makes sense, let me know otherwise.

We have plans to create a proper documentation with this kind of scenarios:
 - https://github.com/mmontes11/mariadb-operator/issues/21
