### ISSUE TITLE
help needed configuration

### ISSUE THREAD

**Issue by fabioportieri** [mmontes11/mariadb-operator#45]
hello
i'm new with kubernetes operators, and i'm not sure i understand how to configure this
i want to configure username, db name and user password, but i'm not sure how to edit config/*.yml , and / or if i have to edit even the samples

thank you in advance

**Comment by mmontes11** [comment]
Hey!

You don't need to edit the samples, they just provide some guidance so you can create your own resources.

First thing will be installing the operator itself in your Kubernetes cluster, check this [section](https://github.com/mmontes11/mariadb-operator#bare-minimum-installation) for doing so.

Once it's up and running you can create a `MariaDB` with default a default database, username and password:
```bash
kubectl apply -f mariadb.yaml`
```
`mariadb.yaml` content:
```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  database: mariadb
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb
    key: password

  image:
    repository: mariadb
    tag: "10.7.4"
    pullPolicy: IfNotPresent

  port: 3306

  volumeClaimTemplate:
    resources:
      requests:
        storage: 100Mi
    storageClassName: standard
    accessModes:
      - ReadWriteOnce

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
```
Does this solve your question?

**Comment by fabioportieri** [comment]
thank you for your quick response

so, given your example, if i want to use mySampleDatabase, with user Pippo and password Pluto, how would i go about it?
i don't undestand how are mariadb-secret.yaml and user-secret.yaml referenced by your sample
(and i don't find username)

```
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
data:
  password: <myPass>
  root-password: <myRootPass>
```

```
apiVersion: v1
kind: Secret
metadata:
  name: user
data:
  password: <myPass?>
```

**Comment by mmontes11** [comment]
> so, given your example, if i want to use mySampleDatabase, with user Pippo and password Pluto, how would i go about it?

As you pointed out, you need first to create the password Secrets, exactly as you suggest! :
```bash
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
data:
  password: <myPass>
  root-password: <myRootPass>
````
if youn want `Pluto` to be the password you need to provide it the previous `password` field.

Then you will reference this secret using its `metadata.name` in the `MariaDB` resource (think it as a foreign key in a relational database):
```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
   .... 
  passwordSecretKeyRef:
    name: mariadb
    key: password
   ....
 ```
 The reason for this is that we don't want the password in plain text inside the CRD, it's sensitive information.
 
 Regarding this:
 > and i don't find username
 
 The `username` is a field of the `MariaDB` CRD, which can go in plain text there, since It's not sensitive information:
 
 ```yaml
 apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
   .... 
  username: Pippo
   ....
```
 
Let me know if this solves your issues. 

Also make sure you subscribe to the releases, we will be releasing a documention site with getting started guides that probably will be of your interest:
- https://github.com/mmontes11/mariadb-operator/issues/21

**Comment by fabioportieri** [comment]
i added an external service in order to reach the db from my host, but can't connect yet

also when i try to setup a different database:


kubectl apply -f ./mariadb-operator/mariadb_v1alpha1_mariadb.yaml

The MariaDB "mariadb" is invalid: spec.database: Invalid value: "fascicolopersonale": 'spec.database' field is inmutable


those are the files and commands i used:

mariadb-secret.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
data:
  password: <base64encodedPass>
  root-password: <base64encodedPass>
```

user-secret.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: user
data:
  password: <base64encodedPass>
```

mariadb_v1alpha1_grant.yaml
```
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: grant
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
  database: "*"
  table: "*"
  username: userFdp
  grantOption: true
```

mariadb_v1alpha1_user.yaml
```
apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: user
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: user
    key: password
  maxUserConnections: 20
```

mariadb_v1alpha1_database.yaml ( is it correct to store dbname in metadata?)
```
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Database
metadata:
  name: fascicolopersonale
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8
  collate: utf8_general_ci

mariadb_v1alpha1_mariadb.yaml:
```
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  labels:
      app: mariadb-app
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
    
  database: fascicolopersonale
  username: userFdp
  passwordSecretKeyRef:
    name: mariadb
    key: password

  image:
    repository: mariadb
    tag: "10.7.4"
    pullPolicy: IfNotPresent

  port: 3306

  volumeClaimTemplate:
    resources:
      requests:
        storage: 100Mi
    storageClassName: standard
    accessModes:
      - ReadWriteOnce

  metrics:
    exporter:
      image:
        repository: prom/mysqld-exporter
        tag: "v0.14.0"
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 300m
          memory: 512Mi
    serviceMonitor:
      prometheusRelease: kube-prometheus-stack
      interval: 10s
      scrapeTimeout: 10s

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

  env:
    - name: TZ
      value: SYSTEM

  envFrom:
    - configMapRef:
        name: mariadb
---
kind: Service
apiVersion: v1
metadata:
    name: mariadb-app
    namespace: default
    labels:
        app: mariadb-app
spec:
    ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
    selector:
        app: fascicolopersonale-app
    type: LoadBalancer
status:
    loadBalancer:
        ingress:
            - ip: 127.0.0.1
```


kubectl apply -f ./mariadb-operator/config
kubectl apply -f ./mariadb-operator/mariadb_v1alpha1_mariadb.yaml
kubectl apply -f ./mariadb-operator/mariadb_v1alpha1_database.yaml
kubectl apply -f ./mariadb-operator/mariadb_v1alpha1_user.yaml
kubectl apply -f ./mariadb-operator/mariadb_v1alpha1_grant.yaml

but as i said when i ran mariadb.yaml with the database reference modified i got error
The MariaDB "mariadb" is invalid: spec.database: Invalid value: "fascicolopersonale": 'spec.database' field is inmutable
i guess because it's not a field that i can change, but when i install the operator with helm it does provide a default deployment file with mariadb, how can i override it?

thanks again

**Comment by mmontes11** [comment]
> i guess because it's not a field that i can change, 

That's correct, `spec.database` is a field that you cannot update, if you want to change it you need to delete the `MariaDB` resource and create a new one with the field `spec.database` set to the new value. 

> but when i install the operator with helm it does provide a default deployment file with mariadb, how can i override it?

The helm chart provides deployments for the [operator](https://github.com/mmontes11/mariadb-operator/blob/main/deploy/charts/mariadb-operator/templates/deployment.yaml) and the [webhook](https://github.com/mmontes11/mariadb-operator/blob/main/deploy/charts/mariadb-operator/templates/webhook-deployment.yaml) but they are not related to the `MariaDB` instances.

try with the following commands and let me know how it goes:
```bash
# delete current MariaDB
kubectl delete -f ./mariadb-operator/mariadb_v1alpha1_mariadb.yaml

# at this point, update the field `spec.database` field in `mariadb_v1alpha1_mariadb.yaml`
vi  ./mariadb-operator/mariadb_v1alpha1_mariadb.yaml

# create a new MariaDB
kubectl apply -f ./mariadb-operator/mariadb_v1alpha1_mariadb.yaml
```

**Comment by fabioportieri** [comment]
yes my bad, i just had to clean up some files, now i managed to bring up all the services
i'm currently trying to externally access my db instance, could you point me to the right direction?

**Comment by fabioportieri** [comment]
i figured it out how to expose an istance of the db, i'll paste it if it helps anyone:

```
apiVersion: v1
kind: Service
metadata:
    name: mariadb-0
spec:
    type: LoadBalancer
    externalTrafficPolicy: Local
    selector:
        statefulset.kubernetes.io/pod-name: mariadb-0
    ports:
        - protocol: TCP
          port: 3306
          targetPort: 3306
```
