### ISSUE TITLE
`ServiceTemplate` to provide `Service` type and annotations

### ISSUE THREAD

**Issue by mmontes11** [mmontes11/mariadb-operator#46]
Be able to provide a `Service` template in the `MariaDB` CRD to customize how it is exposed in the cluster. For example, if we wanted to expose it using [Metallb](https://metallb.universe.tf/usage/example/):
```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
    ....
    service:
       type: LoadBalancer
       annotations:
            metallb.universe.tf/address-pool: sandbox
```
