### ISSUE TITLE
custom my.cnf file

### ISSUE THREAD

**Issue by ox1depl** [mmontes11/mariadb-operator#51]
Hi
I dont see any possibility how to i can use a custom my.cnf file or inject custom configuration for mariadb.
Can any one tell me how to do in this operator ?

**Comment by mmontes11** [comment]
Hey there @ox1depl !

At the moment this is currently supported, but this could be an interesting feature for the following releases. We could ispecify a custom `my.cnf` in the `MariaDB` CRD that will be mounted in the `StatefulSet` as a `Configmap`:

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
    ...
    myCnf: |
       [mysqld]
       bind-address=0.0.0.0
       default_storage_engine=InnoDB
       binlog_format=row
       innodb_autoinc_lock_mode=2
```

Alternatively, the used could be able to provide the `Configmap` straight away:

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
    ...
    myCnfConfigMapKeyRef:
        name: mariadb-config
        key: 'my.cnf'
```

Does this cover your needs?
