### ISSUE TITLE
[Bug] Grant controller fails to grant/revoke privileges if database name contains dashes

### ISSUE THREAD

**Issue by macno** [mmontes11/mariadb-operator#55]
**Describe the bug**

Given the following CRs
```
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Database
metadata:
  name: ak-test
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8
  collate: utf8_general_ci
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: ak-test-user
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: ak-test-user
    key: password
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: ak-test-grant
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL"
  database: "ak-test"
  table: "*"
  username: ak-test-user
  grantOption: false
---
apiVersion: v1
kind: Secret
metadata:
  name: ak-test-user
data:
  password: NjRiYzJlZWYyYzgyN2ZlY2JmYjFiYzMzOWIyMTFkZTQ=
```

the controller fails to add grant with the following error

```
error reconciling in TemplateReconciler: error creating ak-test-grant: 1 error occurred:\n\t* error granting privileges in MariaDB: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-test.* TO 'ak-test-user'@'%' WITH GRANT OPTION'
```

**Expected behaviour**

I expect the controller to successfully assign the grant

**Environment details**:
- Kubernetes version: 1.25.
- mariadb-operator version: mmontes11/mariadb-operator:v0.0.9
- Install method: helm
- Install flavour: recommended
