### ISSUE TITLE
[Feature] Ability to specify the securityContext for the MariaDB instance pod

### ISSUE THREAD

**Issue by Vidalee** [mmontes11/mariadb-operator#62]
**Is your feature request related to a problem? Please describe.**
I wanted to experiment with the operator using AWS EFS volumes, but the folders in this type of volume are owned by user 1000.
When MariaDB starts, it chown the /var/lib/mysql to its user. But it doesn't have the permission to do so, since the folders are owned by user 1000. (`chown: changing ownership of '/var/lib/mysql/': Operation not permitted`).

Running the pod with 
```yaml
securityContext:
  runAsUser: 1000
```
would solve this issue. Unfortunately, while it's possible to define the securityContext for the controller pod and the controller container in the `values.yaml` file, it doesn't seem like it's possible for the MariaDB pod.

**Describe the solution you'd like**
The possibility to define the securityContext of the MariaDB pod in the `values.yaml` file.

**Describe alternatives you've considered**
Exploring the template files of the Helm chart to hardcode the securityContext, without success.

**Additional context**
None.

**Environment details**:
- Kubernetes version: v1.25.6-eks-48e63af
- mariadb-operator version: v0.0.9
- Install method: helm
- Install flavour: minimal

**Comment by mmontes11** [comment]
Hey @Vidalee !

Totally agreed! We are missing this feature. We could support both the `podSecurityContext` (Pod level) and `securityContext` (container level):

```yaml

apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
...
  podSecurityContext:
     fsGroup: 1
     runAsNonRoot: true
  securityContext:
     allowPrivilegeEscalation: false
     capabilities:
       drop:
        - ALL
     readOnlyRootFilesystem: true
     runAsNonRoot: true
... 
``` 

This will be supported in the following release.

Thanks! 🙏🏻
